### ISSUE TITLE
MagicMirror goes to blank (dark)

### ISSUE THREAD

**Issue by cyb0man** [CFenner/MMM-Sonos#18]
I have installed the "node-sonos-http-api" in "/MagicMirror/modules/node-sonos-http-api" and it is working.
I can access the localhost:5005 without any problems.

The "MagicMirror-Sonos-Module" is installed in "/MagicMirror/modules/MagicMirror-Sonos-Module"

I have added;
                {
                        module: 'MagicMirror-Sonos-Module',   
                        position: 'bottom_bar', // you may choose any location
                        config: {}
                }
to config.js

If I comment out these rows MagicMirror starts without problem.
I run MagicMirror in "serveronly" mode.

What have I missed?

**Comment by magicsunday** [comment]
I had also problems running the api and the module.

cd ~
cd MagicMirror
npm install --production jishi/node-sonos-http-api
cd modules
wget https://github.com/CFenner/MagicMirror-Sonos-Module/archive/master.zip
unzip master.zip
mv MagicMirror-Sonos-Module-master sonos
cd ~/MagicMirror/node_modules/sonos-http-api
pm2 start server.js -x --name "http-api"
pm2 dump

The MagicMirror config should contain the module name "sonos"

**Comment by CFenner** [comment]
This is due to the naming of the git repository. I will change this to the common best practice.
